// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzoPadcdC8DxpSa7B5NkFGkvOYBUwvc24',
    appId: '1:871004347158:web:9a7ac68e4796d016a40e37',
    messagingSenderId: '871004347158',
    projectId: 'flutter-test-7b70a',
    authDomain: 'flutter-test-7b70a.firebaseapp.com',
    storageBucket: 'flutter-test-7b70a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPH0MLGrorfT5LiqGBxACGJKyju3e4he4',
    appId: '1:871004347158:android:cde2b1ea9c3a4bcea40e37',
    messagingSenderId: '871004347158',
    projectId: 'flutter-test-7b70a',
    storageBucket: 'flutter-test-7b70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonXXXAy4ZkJpHHLJAhk3bX2AvWBRhQFU',
    appId: '1:871004347158:ios:cf651b8230ff8c38a40e37',
    messagingSenderId: '871004347158',
    projectId: 'flutter-test-7b70a',
    storageBucket: 'flutter-test-7b70a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonXXXAy4ZkJpHHLJAhk3bX2AvWBRhQFU',
    appId: '1:871004347158:ios:cf651b8230ff8c38a40e37',
    messagingSenderId: '871004347158',
    projectId: 'flutter-test-7b70a',
    storageBucket: 'flutter-test-7b70a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
